In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge

In [23]:
df = pd.read_csv('NY-House-Dataset.csv')
df

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op for sale,599000,1,1.000000,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075","222 E 80th St Apt 3AManhattan, NY 10075",New York,New York County,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.774350,-73.955879
4797,Brokered by Mjr Real Estate Llc,Co-op for sale,245000,1,1.000000,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374","97-40 62 Dr Unit LgRego Park, NY 11374",United States,New York,Queens County,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.732538,-73.860152
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op for sale,1275000,1,1.000000,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011","427 W 21st St Unit GardenNew York, NY 10011",United States,New York,New York County,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.745882,-74.003398
4799,Brokered by E Realty International Corp,Condo for sale,598125,2,1.000000,655.000000,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373","91-23 Corona Ave Unit 4GElmhurst, NY 11373",New York,Queens County,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.742770,-73.872752
4800,Brokered by Nyc Realty Brokers Llc,Co-op for sale,349000,1,1.000000,750.000000,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224","460 Neptune Ave Apt 14OBrooklyn, NY 11224",New York,Kings County,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.970949

In [24]:
df.shape

(4801, 17)

In [25]:
df.nunique()

BROKERTITLE                    1036
TYPE                             13
PRICE                          1274
BEDS                             27
BATH                             22
PROPERTYSQFT                   1445
ADDRESS                        4582
STATE                           308
MAIN_ADDRESS                   4583
ADMINISTRATIVE_AREA_LEVEL_2      29
LOCALITY                         11
SUBLOCALITY                      21
STREET_NAME                     174
LONG_NAME                      2731
FORMATTED_ADDRESS              4550
LATITUDE                       4196
LONGITUDE                      4118
dtype: int64

In [26]:
df.dropna(inplace=True)
df

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op for sale,599000,1,1.000000,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075","222 E 80th St Apt 3AManhattan, NY 10075",New York,New York County,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.774350,-73.955879
4797,Brokered by Mjr Real Estate Llc,Co-op for sale,245000,1,1.000000,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374","97-40 62 Dr Unit LgRego Park, NY 11374",United States,New York,Queens County,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.732538,-73.860152
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op for sale,1275000,1,1.000000,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011","427 W 21st St Unit GardenNew York, NY 10011",United States,New York,New York County,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.745882,-74.003398
4799,Brokered by E Realty International Corp,Condo for sale,598125,2,1.000000,655.000000,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373","91-23 Corona Ave Unit 4GElmhurst, NY 11373",New York,Queens County,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.742770,-73.872752
4800,Brokered by Nyc Realty Brokers Llc,Co-op for sale,349000,1,1.000000,750.000000,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224","460 Neptune Ave Apt 14OBrooklyn, NY 11224",New York,Kings County,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.970949

In [27]:
df = pd.get_dummies(df,dtype='int')
df

,PRICE,BEDS,BATH,PROPERTYSQFT,LATITUDE,LONGITUDE,BROKERTITLE_Brokered by 1 Oak Real Estate Hub Inc,BROKERTITLE_Brokered by 5 Boro Realty Corp,BROKERTITLE_Brokered by A J Realty Of Queens Inc,BROKERTITLE_Brokered by A P Services Inc,...,"FORMATTED_ADDRESS_Regis Residence, 2 E 55th St #1118, New York, NY 10022, USA","FORMATTED_ADDRESS_Regis Residence, 2 E 55th St #803, New York, NY 10022, USA","FORMATTED_ADDRESS_Suffolk St, New York, NY 10002, USA","FORMATTED_ADDRESS_T.H.I.S Town House international School, 1199 Park Ave #6j, New York, NY 10128, USA","FORMATTED_ADDRESS_The Belvedere, 84-12 35th Ave #4c, Jackson Heights, NY 11372, USA","FORMATTED_ADDRESS_The Briarcliff, 3515 Henry Hudson Pkwy #3d, Bronx, NY 10463, USA","FORMATTED_ADDRESS_The Police Building, 240 Centre St #2b, New York, NY 10013, USA","FORMATTED_ADDRESS_Tudor City, New York, NY 10017, USA","FORMATTED_ADDRESS_Waldron Ave, Staten Island, NY 10301, USA","FORMATTED_ADDRESS_roosevelt house, 102-40 67th Dr #1b, Flushing, NY 11375, USA"
0,315000,2,2.000000,1400.000000,40.761255,-73.974483,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,195000000,7,10.000000,17545.000000,40.766393,-73.980991,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,260000,4,2.000000,2015.000000,40.541805,-74.196109,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,69000,3,1.000000,445.000000,40.761398,-73.974613,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,55000000,7,2.373861,14175.000000,40.767224,-73.969856,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,599000,1,1.000000,2184.207862,40.774350,-73.955879,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4797,245000,1,1.000000,2184.207862,40.732538,-73.860152,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4798,1275000,1,1.000000,2184.207862,40.745882,-74.003398,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4799,598125,2,1.000000,655.000000,40.742770,-73.872752,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4800,349000,1,1.000000,750.000000,40.579147,-73.970949,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
X = df.drop(columns=['PRICE'])
Y = df['PRICE']
X

,BEDS,BATH,PROPERTYSQFT,LATITUDE,LONGITUDE,BROKERTITLE_Brokered by 1 Oak Real Estate Hub Inc,BROKERTITLE_Brokered by 5 Boro Realty Corp,BROKERTITLE_Brokered by A J Realty Of Queens Inc,BROKERTITLE_Brokered by A P Services Inc,BROKERTITLE_Brokered by AAA Young Shuen Realty Inc,...,"FORMATTED_ADDRESS_Regis Residence, 2 E 55th St #1118, New York, NY 10022, USA","FORMATTED_ADDRESS_Regis Residence, 2 E 55th St #803, New York, NY 10022, USA","FORMATTED_ADDRESS_Suffolk St, New York, NY 10002, USA","FORMATTED_ADDRESS_T.H.I.S Town House international School, 1199 Park Ave #6j, New York, NY 10128, USA","FORMATTED_ADDRESS_The Belvedere, 84-12 35th Ave #4c, Jackson Heights, NY 11372, USA","FORMATTED_ADDRESS_The Briarcliff, 3515 Henry Hudson Pkwy #3d, Bronx, NY 10463, USA","FORMATTED_ADDRESS_The Police Building, 240 Centre St #2b, New York, NY 10013, USA","FORMATTED_ADDRESS_Tudor City, New York, NY 10017, USA","FORMATTED_ADDRESS_Waldron Ave, Staten Island, NY 10301, USA","FORMATTED_ADDRESS_roosevelt house, 102-40 67th Dr #1b, Flushing, NY 11375, USA"
0,2,2.000000,1400.000000,40.761255,-73.974483,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,7,10.000000,17545.000000,40.766393,-73.980991,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,2.000000,2015.000000,40.541805,-74.196109,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1.000000,445.000000,40.761398,-73.974613,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,7,2.373861,14175.000000,40.767224,-73.969856,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,1,1.000000,2184.207862,40.774350,-73.955879,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4797,1,1.000000,2184.207862,40.732538,-73.860152,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4798,1,1.000000,2184.207862,40.745882,-74.003398,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4799,2,1.000000,655.000000,40.742770,-73.872752,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4800,1,1.000000,750.000000,40.579147,-73.970949,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
Y

0          315000
1       195000000
2          260000
3           69000
4        55000000
          ...
4796       599000
4797       245000
4798      1275000
4799       598125
4800       349000
Name: PRICE, Length: 4801, dtype: int64

In [30]:

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [31]:
model_lin = LinearRegression()
model_lin.fit(X_train,Y_train)

LinearRegression()

In [32]:
model_lin.score(X_train,Y_train)

1.0

In [33]:
model_lin.score(X_test,Y_test)

-1.6101533287806769

In [34]:
model_las = Lasso(alpha = 50,max_iter = 100,tol = 0.1)

In [35]:
model_las.fit(X_train,Y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [36]:
model_las.score(X_train,Y_train)

0.9999816616697126

In [37]:
model_las.score(X_test,Y_test)

-1.2332689731398254

In [38]:
model_rid  = Ridge(alpha = 1,max_iter = 1,tol = 0.001)

In [39]:
model_rid.fit(X_train,Y_train)

Ridge(alpha=1, max_iter=1, tol=0.001)

In [40]:
model_rid.score(X_train,Y_train)

0.959834939871609

In [41]:
model_rid.score(X_test,Y_test)

-1.0066474866712607